language: haskell
sudo: false
env:
 - GHCVER=7.6.3 CABALVER=1.18
 - GHCVER=7.8.3 CABALVER=1.18
 - GHCVER=7.10.1 CABALVER=1.22
before_install:
 - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | apt-key add -
 - travis_retry add-apt-repository -y ppa:hvr/ghc
 - travis_retry apt-get update
 - travis_retry apt-get install cabal-install-$CABALVER ghc-$GHCVER
 - wget -P downloads/ http://llvm.org/releases/3.5.1/llvm-3.5.1.src.tar.xz
 - export PATH=/opt/ghc/$GHCVER/bin:/opt/cabal/$CABALVER/bin:$PATH
 - cabal --version
 - sudo /opt/ghc/$GHCVER/bin/ghc-pkg recache
 - /opt/ghc/$GHCVER/bin/ghc-pkg recache --user
 - cabal update
script:
 - runhaskell Shake.hs test

