language: haskell
install:
 - sudo apt-get install libstdc++6
 - mkdir -p llvm/build
 - travis_retry wget -P llvm/ http://llvm.org/releases/3.5.1/llvm-3.5.1.src.tar.xz
 - (cd llvm; tar xf llvm-3.5.1.src.tar.xz; cd build; ../llvm-3.5.1.src/configure --prefix=${PWD}/../install --enable-shared; make install)
 - PATH=${PWD}/llvm/install/bin:${PATH}
 - cabal update
 - cabal install --only-dependencies --enable-tests --force-reinstall llvm-general-pure/ llvm-general/
script:
 - cabal install --enable-tests llvm-general-pure/ llvm-general/
