language: haskell
before_install:
  - sudo sudo sh -c "echo 'deb http://llvm.org/apt/precise/ llvm-toolchain-precise-3.5 main' >> /etc/apt/sources.list"
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - sudo apt-get update -qq
  - sudo apt-get install llvm-3.5-dev
install:
  - cabal install --only-dependencies --enable-tests --force-reinstall llvm-general-pure/ llvm-general/
script:
  - cabal install --enable-tests llvm-general-pure/ llvm-general/
