language: haskell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq llvm-3.3
install:
  - cabal install --only-dependencies --enable-tests --force-reinstall llvm-general-pure/ llvm-general/
script:
  - cabal install --enable-tests llvm-general-pure/ llvm-general/
